packages:
  - apps/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - lefthook

patchedDependencies:
  react-native-litert-lm@0.4.2: patches/react-native-litert-lm@0.4.2.patch
