/**
 * notifee 用の config plugin。2 つの mod を適用する。
 *
 * 1. フォアグラウンドサービスへの connectedDevice タイプ宣言
 *    Android 14 (targetSdk 34) 以降はフォアグラウンドサービスのタイプ宣言が必須。
 *    notifee がライブラリ側マニフェストで宣言しているサービスを tools:replace で
 *    上書きする（notifee 公式ドキュメント「Foreground Service Types」の手順）。
 *    通知側のタイプ指定は src/modules/keepAlive/keepAlive.native.ts にある。
 *
 * 2. notifee 同梱 Maven リポジトリ（app.notifee:core）の明示登録
 *    notifee は自身の build.gradle から rootProject.allprojects でリポジトリを
 *    差し込むが、expo run:android が付ける --configure-on-demand とこの
 *    クロスプロジェクト設定は両立せず、登録が効かないことがある。prebuild 時に
 *    Node の解決で実パス（pnpm hoisted ではリポジトリルートの node_modules）を
 *    求め、android/build.gradle に直接追記して確実にする。
 */
const path = require('node:path');
const { withAndroidManifest, withProjectBuildGradle } = require('expo/config-plugins');

const SERVICE_NAME = 'app.notifee.core.ForegroundService';
const REPO_MARKER = '// @generated by plugins/withNotifeeConnectedDevice.js';

function withConnectedDeviceServiceType(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults.manifest;
    manifest.$ = manifest.$ ?? {};
    manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';

    const application = manifest.application?.[0];
    if (application) {
      application.service = application.service ?? [];
      let service = application.service.find((s) => s.$?.['android:name'] === SERVICE_NAME);
      if (service == null) {
        service = { $: { 'android:name': SERVICE_NAME } };
        application.service.push(service);
      }
      service.$['android:foregroundServiceType'] = 'connectedDevice';
      service.$['tools:replace'] = 'android:foregroundServiceType';
    }
    return mod;
  });
}

function withNotifeeMavenRepo(config) {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error('withNotifeeConnectedDevice: android/build.gradle が groovy ではありません');
    }
    if (!mod.modResults.contents.includes(REPO_MARKER)) {
      const libsDir = path
        .join(
          path.dirname(require.resolve('@notifee/react-native/package.json')),
          'android',
          'libs',
        )
        .replace(/\\/g, '/');
      mod.modResults.contents += [
        '',
        REPO_MARKER,
        'allprojects {',
        '  repositories {',
        `    maven { url("${libsDir}") }`,
        '  }',
        '}',
        '',
      ].join('\n');
    }
    return mod;
  });
}

module.exports = function withNotifeeConnectedDevice(config) {
  return withNotifeeMavenRepo(withConnectedDeviceServiceType(config));
};
